version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  heroku_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: hive_kind_rails_test
          POSTGRES_PASSWORD: ""
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.18.0
      - restore_cache:
          key: hexy-cache-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install

      - save_cache:
          key: hexy-cache-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache

      - restore_cache:
          key: hexy-cache-bundle-{{ checksum "Gemfile.lock" }}

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run:
          name: "Check chromedriver is installed"
          command: |
            chromedriver --version

      - run:
          name: Install bundler dependencies
          command: |
            gem update --system
            gem install bundler

      # Bundle install dependencies
      - run:
          name: Bundle Install
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install

      - save_cache:
          key: hexy-cache-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run:
          name: Setup database from schema
          command: bundle exec rake db:create db:schema:load

      - run:
          name: Precompiler webpacker assets
          command: RAILS_ENV=test bundle exec rails webpacker:compile

      - run:
          name: Run react jest tests
          command: NODE_ENV=test yarn run jest-tests app/javascript/tests/unit/utils.test.js

      - run:
          name: Run Rspec tests
          command: bundle exec rspec

