module PagesHelper

	def clean_hex_array(hexes:, is_in_editing_mode: false)
    return hexes.map{ |t| {
				draft: t.draft,
				order: t.order,
				trixel_colour_a1: !t.draft || is_in_editing_mode ? t.trixel_colour_a1 : "#fff",
				trixel_colour_a2: !t.draft || is_in_editing_mode ? t.trixel_colour_a2 : "#fff",
				trixel_colour_a3: !t.draft || is_in_editing_mode ? t.trixel_colour_a3 : "#fff",
				trixel_colour_a4: !t.draft || is_in_editing_mode ? t.trixel_colour_a4 : "#fff",
				trixel_colour_a5: !t.draft || is_in_editing_mode ? t.trixel_colour_a5 : "#fff",
				trixel_colour_a6: !t.draft || is_in_editing_mode ? t.trixel_colour_a6 : "#fff",
				trixel_colour_a7: !t.draft || is_in_editing_mode ? t.trixel_colour_a7 : "#fff",
				trixel_colour_b1: !t.draft || is_in_editing_mode ? t.trixel_colour_b1 : "#fff",
				trixel_colour_b2: !t.draft || is_in_editing_mode ? t.trixel_colour_b2 : "#fff",
				trixel_colour_b3: !t.draft || is_in_editing_mode ? t.trixel_colour_b3 : "#fff",
				trixel_colour_b4: !t.draft || is_in_editing_mode ? t.trixel_colour_b4 : "#fff",
				trixel_colour_b5: !t.draft || is_in_editing_mode ? t.trixel_colour_b5 : "#fff",
				trixel_colour_b6: !t.draft || is_in_editing_mode ? t.trixel_colour_b6 : "#fff",
				trixel_colour_b7: !t.draft || is_in_editing_mode ? t.trixel_colour_b7 : "#fff",
				trixel_colour_b8: !t.draft || is_in_editing_mode ? t.trixel_colour_b8 : "#fff",
				trixel_colour_b9: !t.draft || is_in_editing_mode ? t.trixel_colour_b9 : "#fff",
				trixel_colour_c1: !t.draft || is_in_editing_mode ? t.trixel_colour_c1 : "#fff",
				trixel_colour_c2: !t.draft || is_in_editing_mode ? t.trixel_colour_c2 : "#fff",
				trixel_colour_c3: !t.draft || is_in_editing_mode ? t.trixel_colour_c3 : "#fff",
				trixel_colour_c4: !t.draft || is_in_editing_mode ? t.trixel_colour_c4 : "#fff",
				trixel_colour_c5: !t.draft || is_in_editing_mode ? t.trixel_colour_c5 : "#fff",
				trixel_colour_c6: !t.draft || is_in_editing_mode ? t.trixel_colour_c6 : "#fff",
				trixel_colour_c7: !t.draft || is_in_editing_mode ? t.trixel_colour_c7 : "#fff",
				trixel_colour_c8: !t.draft || is_in_editing_mode ? t.trixel_colour_c8 : "#fff",
				trixel_colour_c9: !t.draft || is_in_editing_mode ? t.trixel_colour_c9 : "#fff",
				trixel_colour_c10: !t.draft || is_in_editing_mode ? t.trixel_colour_c10 : "#fff",
				trixel_colour_c11: !t.draft || is_in_editing_mode ? t.trixel_colour_c11 : "#fff",
				trixel_colour_d1: !t.draft || is_in_editing_mode ? t.trixel_colour_d1 : "#fff",
				trixel_colour_d2: !t.draft || is_in_editing_mode ? t.trixel_colour_d2 : "#fff",
				trixel_colour_d3: !t.draft || is_in_editing_mode ? t.trixel_colour_d3 : "#fff",
				trixel_colour_d4: !t.draft || is_in_editing_mode ? t.trixel_colour_d4 : "#fff",
				trixel_colour_d5: !t.draft || is_in_editing_mode ? t.trixel_colour_d5 : "#fff",
				trixel_colour_d6: !t.draft || is_in_editing_mode ? t.trixel_colour_d6 : "#fff",
				trixel_colour_d7: !t.draft || is_in_editing_mode ? t.trixel_colour_d7 : "#fff",
				trixel_colour_d8: !t.draft || is_in_editing_mode ? t.trixel_colour_d8 : "#fff",
				trixel_colour_d9: !t.draft || is_in_editing_mode ? t.trixel_colour_d9 : "#fff",
				trixel_colour_d10: !t.draft || is_in_editing_mode ? t.trixel_colour_d10 : "#fff",
				trixel_colour_d11: !t.draft || is_in_editing_mode ? t.trixel_colour_d11 : "#fff",
				trixel_colour_e1: !t.draft || is_in_editing_mode ? t.trixel_colour_e1 : "#fff",
				trixel_colour_e2: !t.draft || is_in_editing_mode ? t.trixel_colour_e2 : "#fff",
				trixel_colour_e3: !t.draft || is_in_editing_mode ? t.trixel_colour_e3 : "#fff",
				trixel_colour_e4: !t.draft || is_in_editing_mode ? t.trixel_colour_e4 : "#fff",
				trixel_colour_e5: !t.draft || is_in_editing_mode ? t.trixel_colour_e5 : "#fff",
				trixel_colour_e6: !t.draft || is_in_editing_mode ? t.trixel_colour_e6 : "#fff",
				trixel_colour_e7: !t.draft || is_in_editing_mode ? t.trixel_colour_e7 : "#fff",
				trixel_colour_e8: !t.draft || is_in_editing_mode ? t.trixel_colour_e8 : "#fff",
				trixel_colour_e9: !t.draft || is_in_editing_mode ? t.trixel_colour_e9 : "#fff",
				trixel_colour_f1: !t.draft || is_in_editing_mode ? t.trixel_colour_f1 : "#fff",
				trixel_colour_f2: !t.draft || is_in_editing_mode ? t.trixel_colour_f2 : "#fff",
				trixel_colour_f3: !t.draft || is_in_editing_mode ? t.trixel_colour_f3 : "#fff",
				trixel_colour_f4: !t.draft || is_in_editing_mode ? t.trixel_colour_f4 : "#fff",
				trixel_colour_f5: !t.draft || is_in_editing_mode ? t.trixel_colour_f5 : "#fff",
				trixel_colour_f6: !t.draft || is_in_editing_mode ? t.trixel_colour_f6 : "#fff",
				trixel_colour_f7: !t.draft || is_in_editing_mode ? t.trixel_colour_f7 : "#fff",
				country_code: t.country_code
			}
    }
	end


end
