class MoveTrixelColumnsIntoTile < ActiveRecord::Migration[6.1]
  def change
    add_column :tiles, :trixel_colour_a1, :string, default: "#fff"
    add_column :tiles, :trixel_colour_a2, :string, default: "#fff"
    add_column :tiles, :trixel_colour_a3, :string, default: "#fff"
    add_column :tiles, :trixel_colour_a4, :string, default: "#fff"
    add_column :tiles, :trixel_colour_a5, :string, default: "#fff"
    add_column :tiles, :trixel_colour_a6, :string, default: "#fff"
    add_column :tiles, :trixel_colour_a7, :string, default: "#fff"

    add_column :tiles, :trixel_colour_b1, :string, default: "#fff"
    add_column :tiles, :trixel_colour_b2, :string, default: "#fff"
    add_column :tiles, :trixel_colour_b3, :string, default: "#fff"
    add_column :tiles, :trixel_colour_b4, :string, default: "#fff"
    add_column :tiles, :trixel_colour_b5, :string, default: "#fff"
    add_column :tiles, :trixel_colour_b6, :string, default: "#fff"
    add_column :tiles, :trixel_colour_b7, :string, default: "#fff"
    add_column :tiles, :trixel_colour_b8, :string, default: "#fff"
    add_column :tiles, :trixel_colour_b9, :string, default: "#fff"

    add_column :tiles, :trixel_colour_c1, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c2, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c3, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c4, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c5, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c6, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c7, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c8, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c9, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c10, :string, default: "#fff"
    add_column :tiles, :trixel_colour_c11, :string, default: "#fff"

    add_column :tiles, :trixel_colour_d1, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d2, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d3, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d4, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d5, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d6, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d7, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d8, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d9, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d10, :string, default: "#fff"
    add_column :tiles, :trixel_colour_d11, :string, default: "#fff"

    add_column :tiles, :trixel_colour_e1, :string, default: "#fff"
    add_column :tiles, :trixel_colour_e2, :string, default: "#fff"
    add_column :tiles, :trixel_colour_e3, :string, default: "#fff"
    add_column :tiles, :trixel_colour_e4, :string, default: "#fff"
    add_column :tiles, :trixel_colour_e5, :string, default: "#fff"
    add_column :tiles, :trixel_colour_e6, :string, default: "#fff"
    add_column :tiles, :trixel_colour_e7, :string, default: "#fff"
    add_column :tiles, :trixel_colour_e8, :string, default: "#fff"
    add_column :tiles, :trixel_colour_e9, :string, default: "#fff"

    add_column :tiles, :trixel_colour_f1, :string, default: "#fff"
    add_column :tiles, :trixel_colour_f2, :string, default: "#fff"
    add_column :tiles, :trixel_colour_f3, :string, default: "#fff"
    add_column :tiles, :trixel_colour_f4, :string, default: "#fff"
    add_column :tiles, :trixel_colour_f5, :string, default: "#fff"
    add_column :tiles, :trixel_colour_f6, :string, default: "#fff"
    add_column :tiles, :trixel_colour_f7, :string, default: "#fff"
  end
end
