class UpdateTrixelColourDefault < ActiveRecord::Migration[6.1]
  def change
    change_column_default :hexes, :trixel_colour_a1, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_a2, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_a3, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_a4, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_a5, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_a6, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_a7, "#FFFFFF"

    change_column_default :hexes, :trixel_colour_b1, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_b2, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_b3, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_b4, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_b5, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_b6, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_b7, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_b8, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_b9, "#FFFFFF"

    change_column_default :hexes, :trixel_colour_c1, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c2, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c3, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c4, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c5, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c6, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c7, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c8, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c9, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c10, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_c11, "#FFFFFF"

    change_column_default :hexes, :trixel_colour_d1, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d2, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d3, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d4, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d5, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d6, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d7, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d8, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d9, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d10, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_d11, "#FFFFFF"

    change_column_default :hexes, :trixel_colour_e1, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_e2, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_e3, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_e4, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_e5, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_e6, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_e7, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_e8, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_e9, "#FFFFFF"

    change_column_default :hexes, :trixel_colour_f1, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_f2, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_f3, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_f4, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_f5, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_f6, "#FFFFFF"
    change_column_default :hexes, :trixel_colour_f7, "#FFFFFF"
  end
end
